{
 "title": "Hydrozoa - Alice peer",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Head peers uptime",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "headUptime", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "L2 Event Pool",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "poolEventsL2{job=\"alice\"}",
     "legendFormat": "{{eventType}}"
    }
   ]
  },
  {
   "title": "Block distribution by types",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockNum{job=\"alice\", blockType!=\"total\"}",
     "legendFormat": "Blocks {{label_name}}{{blockType}}"
    }
   ]
  },
  {
   "title": "Deposits absorbed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deposits_total{job=\"alice\", state=\"absorbed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deposits absorbed,₳",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "volume_total{job=\"alice\", volumeType=\"inboundL1\"} / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Settlement AVG fees, ₳",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_avg(rate(costs{job=\"alice\", costType=\"settlement\"}[$__rate_interval])) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L2 invalid events",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eventsL2Handled_total{job=\"alice\", eventValidity=\"invalid\"}",
     "legendFormat": "{{eventType}}"
    }
   ]
  },
  {
   "title": "Deposit queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "depositQueueSize{job=\"alice\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "L2 Txs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eventsL2Handled_total{job=\"alice\", eventValidity=\"valid\", eventType=\"transaction\"}",
     "legendFormat": "{{eventType}}"
    }
   ]
  },
  {
   "title": "L2 Tx Volume, ₳",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "volume_total{job=\"alice\", volumeType=\"transactedL2\"} / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Head liquidity, ₳",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "liquidity{job=\"alice\"} / 1000000",
     "legendFormat": "Liquidity {{label_name}}{{utxoType}}"
    }
   ]
  },
  {
   "title": "Settlement costs, lovelaces",
   "type": "histogram",
   "gridPos": { "h": 13, "w": 4, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(costs{instance=\"alice:9400\", costType=\"settlement\"}[1h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L2 withdrawals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eventsL2Handled_total{job=\"alice\", eventValidity=\"valid\", eventType=\"withdrawal\"}",
     "legendFormat": "{{eventType}}"
    }
   ]
  },
  {
   "title": "Volume withdrawn, ₳",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "volume_total{job=\"alice\", volumeType=\"outboundL1\"} / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total L1 fees, ₳",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "volume_total{job=\"alice\", volumeType=\"feesL1\"} / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "blockNum{blockType=\"total\", job=\"alice\"}",
     "legendFormat": "Total blocks"
    },
    {
     "expr": "blockNum{blockType=\"major\", job=\"alice\"}",
     "legendFormat": "Major blocks"
    },
    {
     "expr": "blockNum{blockType=\"minor\", job=\"alice\"}",
     "legendFormat": "Minor blocks"
    }
   ]
  }
 ]
}