x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"
    tag: "{{.Name}}"

services:

  alice:
    image: cardano-hydrozoa/hydrozoa:0.1.0-SNAPSHOT
    container_name: hydrozoa-alice
    hostname: alice
    command:
      - Alice
      - "8093"
      - "9400"
    ports:
      - 8093:8093
      - 9403:9400
    expose:
      - 4937
    logging: *default-logging
    networks:
      hydrozoa_network:

  bob:
    image: cardano-hydrozoa/hydrozoa:0.1.0-SNAPSHOT
    container_name: hydrozoa-bob
    hostname: bob
    command:
      - Bob
      - "8094"
      - "9400"
    ports:
      - 8094:8094
      - 9404:9400
    expose:
      - 4938
    depends_on:
      - alice
    logging: *default-logging
    networks:
      hydrozoa_network:

  carol:
    image: cardano-hydrozoa/hydrozoa:0.1.0-SNAPSHOT
    container_name: hydrozoa-carol
    hostname: carol
    command:
      - Carol
      - "8095"
      - "9400"
    ports:
      - 8095:8095
      - 9405:9400
    expose:
      - 4939
    depends_on:
      - alice
      - bob
    logging: *default-logging
    networks:
      hydrozoa_network:

  yaci-cli:
    image: bloxbean/yaci-cli:0.10.5
    container_name: yaci-cli
    hostname: yaci-cli
    ports:
      - 3001:3001
      - 3333:3333
      - 8090:8090
      - 8080:8080
      - 10000:10000
      - 1337:1337
      - 1442:1442
    volumes:
      - cluster-data:/clusters
      - ./yaci/node.properties:/app/config/node.properties
    env_file:
      - ./yaci/node.properties
      - ./yaci/env
    entrypoint: ["/app/yaci-cli.sh", "create-node", "-o", "--start"]
    networks:
      hydrozoa_network:

  yaci-viewer:
    image: bloxbean/yaci-viewer:0.10.5
    container_name: yaci-viewer
    hostname: yaci-viewer
    ports:
      - 5173:5173
    env_file:
      - ./yaci/env
    networks:
      hydrozoa_network:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    user: root
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --storage.tsdb.path=/prometheus
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus
    logging: *default-logging
    networks:
      hydrozoa_network:
  
  loki:
    container_name: loki
    image: grafana/loki:3.4.1
    ports:
      - 3100:3100
    command:
      - -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml:ro
    logging: *default-logging
    networks:
      hydrozoa_network:
  
  promtail:
    image: grafana/promtail:2.7.1
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
      # - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki
    networks:
      hydrozoa_network:

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    hostname: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    logging: *default-logging
    networks:
      hydrozoa_network:

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3003:3000
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - DS_PROMETHEUS=prometheus
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor metricsSummary
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboard.json:/var/lib/grafana/dashboards/dashboard.json
      - ./grafana/default.yaml:/etc/grafana/provisioning/dashboards/default.yaml
    depends_on:
      - prometheus
      - loki
    logging: *default-logging
    networks:
      hydrozoa_network:

  tempo-init:
    container_name: tempo-init
    image: grafana/tempo:latest
    user: root
    entrypoint:
      - chown
      - 10001:10001
      - /var/tempo
    volumes:
      - ./tempo-data:/var/tempo
    networks:
      hydrozoa_network:

  tempo:
    container_name: tempo
    image: grafana/tempo:latest
    command: [-config.file=/etc/tempo.yaml]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    ports:
      - 14268:14268  # jaeger ingest
      - 3200:3200    # tempo
      - 9095:9095    # tempo grpc
      - 4317:4317    # otlp grpc
      - 4318:4318    # otlp http
      - 9411:9411    # zipkin
    depends_on:
      - tempo-init
    logging: *default-logging
    networks:
      hydrozoa_network:

networks:
  hydrozoa_network:

volumes:
  grafana-data:
    driver: local
  prometheus-data:
    driver: local
  tempo-data:
    driver: local
  cluster-data:
    driver: local
